docker-compose-yaml: docker-compose.yml

project: drupal-seed

ssh: token.main.lagoon-core.test6.amazee.io:22
api: https://api.main.lagoon-core.test6.amazee.io/graphql

environment_variables:
  git_sha: 'true'

tasks:
  pre-rollout:
    - run:
        name: Always write cluster id to pre-rollout file
        command: echo $LAGOON_KUBERNETES > /app/web/sites/default/files/test-0-pre-rollout
        service: cli
        shell: bash
        when: exists("LAGOON_KUBERNETES")
  post-rollout:
    - run:
        name: install a fresh Drupal site
        # This will only run if the database doesn't exist. The `_` is a fallback for empty value`
        command: |
          if [[ _$(drush status --field='Drupal bootstrap') != "_Successful" ]]; then drush -y si; fi
        service: cli
    - run:
        name: set site name
        command: |
          if [[ $(drush status --field=Database) == "Connected" ]]; then drush -y cset system.site name "environment $LAGOON_ENVIRONMENT running on $LAGOON_KUBERNETES"; fi
        service: cli
    - run:
        name: drush updb
        # This will only run if the database exists.
        command: |
          if [[ $(drush status --field=Database) == "Connected" ]]; then drush -y updb; fi
        service: cli
    - run:
        name: drush cr
        # This will only run if the database exists.
        command: |
          if [[ $(drush status --field=Database) == "Connected" ]]; then drush -y cr; fi
        service: cli
        shell: bash

environments:
  main:
    # routes:
    cronjobs:
      - name: drush hourly cron
        schedule: "M * * * *"
        command: drush cron --debug
        service: cli
