docker-compose-yaml: docker-compose.yml

project: drupal-seed

ssh: token.main.lagoon-core.test6.amazee.io:22
api: https://api.main.lagoon-core.test6.amazee.io/graphql

environment_variables:
  git_sha: 'true'

tasks:
  pre-rollout:
    - 
      run:
        name: Always write cluster id to pre-rollout file
        command: echo $LAGOON_KUBERNETES > /app/web/sites/default/files/test-0-pre-rollout
        service: cli
        shell: bash
        when: exists("LAGOON_KUBERNETES")
  post-rollout:
    -
      run:
        name: install a fresh Drupal site
        command: drush -y si
        service: cli
    -
      run:
        name: set site name
        command: drush -y cset system.site name "environment $LAGOON_ENVIRONMENT running on $LAGOON_KUBERNETES"
        service: cli
    -
      run:
        name: drush updb
        command: drush -y updb
        service: cli
    - 
      run:
        name: drush cr
        command: drush -y cr
        service: cli

environments:
  main:
    # routes:
    cronjobs:
      - name: drush cron
        schedule: "*/30 * * * *"
        command: drush cron --debug
        service: cli
